### PR TITLE
Small markdown fixes

### PR DESCRIPTION
**Pull request by prometheas**
The main fix here is for the document title, but I have a markdown linter installed, so I simply went about appeasing it until it ran out of things to say 😄

### CODE REVIEW

**Review by jirihybek — APPROVED** [review]

**Comment by jirihybek** [comment]
Thank you for the fix. Is there any way how to update this readme in NPM without republishing the package with increased version number?

**Comment by prometheas** [comment]
Unfortunately, no. I've started work on modification that introduces an option not to mutate unknown shortcodes, but I discovered it's less trivial than it first seemed… 😉

**Comment by jirihybek** [comment]
I've looked at it and it really seems complicated... for now I don't see the right solution to stop mutating undefined shortcodes.

**Comment by prometheas** [comment]
Seems you'd need to refactor the buffered parsing to build an AST, rather than render in flight, since some decisions about how to evaluate character sequences can only reliably be evaluated with insight into what comes "later" in the doc.

Sometimes, for example, square brackets are merely editorial commentary, such as `[sic.]` or help contextualize a quoted string.

From there, you'd do a rendering crawl of the tree.

**Pull request merged**
